# - name: Install caddy
#   hosts: websites
#   tasks:
#     - name: Install caddy package
#       ansible.builtin.package:
#         name: caddy
#         state: present

#     - name: Ensure caddy service is enabled and running
#       ansible.builtin.systemd:
#         name: caddy
#         enabled: true
#         state: started

- name: Configure caddy
  hosts: websites
  tasks:
    - name: Copy Caddyfile file to server
      become: "{{ not ansible_check_mode }}"
      ansible.builtin.copy:
        src: Caddyfile
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: '0644'

    - name: Reload caddy
      become: "{{ not ansible_check_mode }}"
      ansible.builtin.systemd_service:
        name: caddy
        state: reloaded

    - name: Restart caddy
      become: "{{ not ansible_check_mode }}"
      ansible.builtin.systemd_service:
        name: caddy
        state: restarted
