- name: Create www-be user and www folder
  hosts: websites
  become: "{{ not ansible_check_mode }}"
  tasks:
    - name: Ensure user exists with home
      ansible.builtin.user:
        name: www-be
        create_home: yes

    - name: Ensure home folder exists and has correct permissions
      ansible.builtin.file:
        path: /home/www-be
        state: directory
        owner: www-be
        group: www-be
        mode: '0755'

    - name: Ensure www folder exists and has correct permissions
      ansible.builtin.file:
        path: /home/www-be/www
        state: directory
        owner: www-be
        group: www-be
        mode: '0755'

    - name: Add index.html file
      ansible.builtin.copy:
        src: ../placeholders/bald-wieder-da.html
        dest: /home/www-be/www/index.html
        owner: www-be
        group: www-be
        mode: '0644'
